name: Scrape Avito Reviews

on:
  schedule:
    # Запускаем каждый понедельник в 9:00 UTC (12:00 по Москве)
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Позволяет запускать вручную
  push:
    branches: [ main ]

jobs:
  scrape-reviews:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Скачиваем код
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 🐍 Устанавливаем Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 📦 Устанавливаем зависимости
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 🚀 Запускаем парсер отзывов
      run: |
        python scraper.py
        
    - name: 📊 Показываем результат
      run: |
        echo "=== РЕЗУЛЬТАТ РАБОТЫ ПАРСЕРА ==="
        cat reviews.json
        echo "================================="
        
    - name: 💾 Сохраняем изменения
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add reviews.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Авто-обновление отзывов [$(date +%Y-%m-%d)]" && git push)
