name: Scrape Avito Reviews

on:
  schedule:
    # Запускаем каждый понедельник в 9:00 утра
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  scrape-reviews:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: 📥 Скачиваем код
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 🐍 Устанавливаем Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 📦 Устанавливаем зависимости
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 🚀 Запускаем сбор отзывов
      run: |
        python scraper.py
        
    - name: 📊 Показываем результат
      run: |
        echo "=== РЕЗУЛЬТАТ РАБОТЫ ==="
        ls -la reviews.json
        echo "Первые 500 символов файла:"
        head -c 500 reviews.json
        echo ""
        
    - name: 💾 Настраиваем Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: 📝 Коммитим изменения
      run: |
        git add reviews.json
        # Проверяем есть ли изменения
        if git diff --staged --quiet; then
          echo "🔄 Нет изменений для коммита"
        else
          git commit -m "🤖 Авто-обновление отзывов [$(date +%Y-%m-%d)]"
          echo "✅ Изменения закоммичены"
        fi
        
    - name: 🚀 Пушим изменения
      run: |
        # Пробуем сделать push с принудительной перезаписой истории (аккуратно)
        git pull --rebase origin main
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
